- bookid: "97897" # 武帝隐居之后的生活
  issend: false
  groupid:
  - 712867932
  recordurl: ""
- bookid: "263756"  # 转世魔王绝对不娶青梅竹马勇者
  issend: true
  groupid:
  - 970674233
  recordurl: ""
- bookid: "154390"  # 领主什么的无所谓啦
  issend: true
  groupid:
  - 1102946382
  - 771435835
  recordurl: ""
- bookid: "179171"  # 当只小鸡丶从入门到精通
  issend: true
  groupid:
  - 1037910244
  recordurl: ""
- bookid: "292551"  # 在充满怪谈的世界里成为魔女
  issend: true
  groupid:
  - 256782902
  - 740484020
  recordurl: ""
- bookid: "292332"  # 我的女徒弟们都是未来诸天大佬
  issend: true
  groupid:
  - 712867932
  recordurl: ""
- bookid: "217202"  # 来自深渊的我今天也要拯救人类
  issend: true
  groupid:
  - 107938027
  recordurl: ""
- bookid: "266927"  # 为了活命我娶了美少女主角
  issend: true
  groupid:
  - 414305080
  recordurl: ""
- bookid: "291397"  # 天才剑仙的徒弟为何是我这个废柴
  issend: false
  groupid:
  - 535191056
  recordurl: ""
- bookid: "340775"  # 在异界化身女仆与弟弟的幸福生活
  issend: false
  groupid:
  - 878661216
  recordurl: ""
- bookid: "420444"  # 魔女的我被圣骑姬俘获之夜
  issend: true
  groupid:
  - 131435688
  - 528814815
  recordurl: ""
- bookid: "431577"  # 在我的直播间吃狗粮爽吗
  issend: true
  groupid:
  - 729205310
  recordurl: ""
- bookid: "358365"  # 穿越后的我把男主女友们全掰弯了
  issend: true
  groupid:
  - 102976190
  recordurl: ""
- bookid: "264866"  # 这个玩穿越的明明超弱却过度自信
  issend: false
  groupid:
  - 136471730
  recordurl: ""
- bookid: "431493"  # 校花吾姐求放过
  issend: true
  groupid:
  - 722038986
  - 936418447
  recordurl: ""
- bookid: "444856"  # 女帝的冒牌天师
  issend: true
  groupid:
  - 514412677
  recordurl: ""
- bookid: "447395"  # 谁想和你们一起修仙啊
  issend: true
  groupid:
  - 414305080
  recordurl: ""
